---
- name: Download Docker installation files
  hosts: localhost
  connection: local
  gather_facts: false
  become: yes
  vars_prompt:
    - name: ansible_become_pass
      prompt: "Enter sudo password"
      private: yes
  tasks:
    - name: Install required packages for adding Docker repository
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Update apt package index
      apt:
        update_cache: yes
        
    - name: Create directory for Docker images
      local_action:
        module: file
        path: /tmp/dockerimages
        state: directory
        mode: '0755'

          
    - name: Download Docker package files
      get_url:
        url: "https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/amd64/{{ item }}"
        dest: /tmp/dockerimages
      with_items:
        - docker-ce_26.1.4-1~ubuntu.22.04~jammy_amd64.deb
        - docker-ce-cli_26.1.4-1~ubuntu.22.04~jammy_amd64.deb
        - containerd.io_1.6.28-1_amd64.deb
      ignore_errors: yes

      
    - name: Install Docker package files
      apt:
        deb: "/tmp/dockerimages/{{ item }}"
      with_items:
        - docker-ce_26.1.4-1~ubuntu.22.04~jammy_amd64.deb
        - docker-ce-cli_26.1.4-1~ubuntu.22.04~jammy_amd64.deb
        - containerd.io_1.6.28-1_amd64.deb


    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes
