# playbooks/install_docker.yml

---
- name: Download Docker Installation Files
  hosts: ubuntu
  tasks:
    - name: Download Docker installation script
      get_url:
        url: https://get.docker.com/
        dest: /tmp/get-docker.sh
      register: download_result

    - name: Check if download was successful
      debug:
        msg: "Download result: {{ download_result }}"

- name: Copy Docker Installation Files to Other Machines
  hosts: all
  tasks:
    - name: Copy Docker installation script from downloader
      fetch:
        src: /tmp/get-docker.sh
        dest: /tmp/
        flat: yes
      delegate_to: downloader

#     - name: Ensure /tmp directory exists on target
#       file:
#         path: /tmp
#         state: directory

#     - name: Copy Docker installation script to targets
#       copy:
#         src: /tmp/get-docker.sh
#         dest: /tmp/get-docker.sh

#     - name: Install Docker on target machines
#       shell: sh /tmp/get-docker.sh
#       become: yes
#       args:
#         creates: /usr/bin/docker
