---
- name: Download Docker installation files
  hosts: ubuntu
  become: yes

  tasks:
    - name: Install required packages for adding Docker repository
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Download Docker package files
      get_url:
        url: "https://download.docker.com/linux/ubuntu/dists/{{ ansible_distribution_release }}/pool/stable/amd64/{{ item }}"
        dest: /tmp/docker-packages/
      with_items:
        - docker-ce_20.10.7~3-0~ubuntu-{{ ansible_distribution_release }}_amd64.deb
        - docker-ce-cli_20.10.7~3-0~ubuntu-{{ ansible_distribution_release }}_amd64.deb
        - containerd.io_1.4.6-1_amd64.deb
      ignore_errors: yes
