---
- name: Download Docker installation files
  hosts: localhost
  connection: local
  gather_facts: false
  become: yes
  vars_prompt:
    - name: ansible_become_pass
      prompt: "Enter sudo password"
      private: yes
  tasks:
    - name: Install required packages for adding Docker repository
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Update apt package index
      apt:
        update_cache: yes
        
    - name: Create directory for Docker images
      local_action:
        module: file
        path: /tmp/dockerimage
        state: directory
        mode: '0755'

    - name: Download Docker package files
      get_url:
        url: "https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/arm64/{{ item }}"
        dest: /tmp/dockerimage
      with_items:
        - docker-ce_26.1.4-1~ubuntu.22.04~jammy_arm64.deb
        - docker-ce-cli_26.1.4-1~ubuntu.22.04~jammy_arm64.deb
        - containerd.io_1.6.28-1_arm64.deb
      ignore_errors: yes
- name: Install Docker packages
  hosts: ubuntu
  become: yes

  tasks:
    - name: Ensure directory exists for Docker images on all hosts
      file:
        path: /tmp/dockerimage
        state: directory
        mode: '0755'
    - name: Debug contents of /tmp/dockerimage on localhost
      debug:
        msg: "{{ lookup('fileglob', '/tmp/dockerimage/*') }}"
      run_once: true

    - name: Copy Docker packages to all hosts
      copy:
        src: /tmp/dockerimage/
        dest: /tmp/dockerimage/
        remote_src: no


    - name: Debug contents of /tmp/dockerimages on remote hosts
      debug:
        msg: "{{ lookup('fileglob', '/tmp/dockerimage/*') }}"
      delegate_to: localhost
    - name: Uninstall containerd.io
      apt:
        name: containerd.io
        state: absent
    - name: Install Docker packages on all hosts
      apt:
        deb: /tmp/dockerimage/{{ item }}
      with_items:
        - docker-ce_26.1.4-1~ubuntu.22.04~jammy_arm64.deb
        - docker-ce-cli_26.1.4-1~ubuntu.22.04~jammy_arm64.deb
        - containerd.io_1.6.28-1_arm64.deb
      ignore_errors: yes
    - name: Set permissions on /var/run/docker.sock
      ansible.builtin.file:
        path: /var/run/docker.sock
        mode: '0666'
        state: file
