---
# YAML documents begin with the document separator ---

# The minus in YAML this indicates a list item.  The playbook contains a list
# of plays, with each play being a dictionary
-

  # Hosts: where our play will run and options it will run with
  hosts: localhost
  connection: local
  gather_facts: false

  # Vars: variables that will apply to the play, on all target system
  vars:
    desired_instances: 20

  # Tasks: the list of tasks that will be executed within the play, this section
  # can also be used for pre and post tasks
  tasks:
    - name: Create a security group in AWS for SSH access and HTTP
      ec2_group:
         name: ansible
         description: Ansible Security Group
         region: us-east-1
         rules:
            - proto: tcp
              from_port: 80
              to_port: 80
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0

    # Capture all instances that already have a tag of Ansible
    - name: Gather information about existing instances
      ec2_instance_info:
        filters:
          "tag:Name": Ansible
          instance-state-name: running
        region: us-east-1
      register: ec2_info

    # Compare the number of instances to launch vs those available, avoid negative numbers
    - name: Calculate the number of instances to launch
      set_fact:
        # Ensure it is never less than zero
        instances_to_launch: "{{ [0, desired_instances - (ec2_info.instances | length)] | max }}"

    # Even with zero instances requested, this needs to be executed 
    # to populate information about existing instances
    - name: Provision a set of instances and/or capture existing information
      ec2_instance:
        key_name: ansible
        name: Ansible
        security_group: ansible
        instance_type: t2.micro
        image_id: ami-0fe630eb857a6ec83
        region: us-east-1
        wait: true
        count: "{{ instances_to_launch }}"
      register: ec2

    - name: Add all instance public IPs to host group
      add_host:
        hostname: "{{ item.public_ip_address }}"
        groups: ansiblehosts
      with_items: "{{ ec2.instances }}"

    - name: Show group
      debug:
        var: groups.ansiblehosts

# Three dots indicate the end of a YAML document
...
